config/routes.rb
Sample::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout',
    :password => 'secret', :confirmation => 'verification', :registration => 'register' }, :controllers => {:registrations => "authentication"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users do
    member do
      put 'toggle_status'
    end
  end

  resources :solutions do
    member do
      put 'toggle_status'
    end
    collection do
      get 'search_authors'
      get 'search_specs'
    end
  end

  resources :home

  resources :solution_specializations do
    member do
      put 'toggle_status'
    end
  end
end

app/models/solution_specialization.rb
class SolutionSpecialization < ActiveRecord::Base

  ### VALIDATIONS ####
  validates_presence_of :title
  validates_length_of :title, :maximum => 255

  before_destroy :can_destroy?
  before_save :can_unpublish?


  ### ASSOCIATIONS ###
  belongs_to :author, :class_name => :User
  has_and_belongs_to_many :solutions, :join_table => "solutions_specs", :foreign_key => "spec_id"


  scope :search, lambda { |keyword, type|
    where("LOWER(title) LIKE ? #{'and solution_specializations.published = TRUE' if type != 'all'}", "%#{keyword.downcase}%")
  }

  ### FUNCTIONS ###
  #Change status of this solution from published to unpublished vice versa
  def toggle_status
    if can_unpublish?
      self.published = !published
      self.save
    else
      return false
    end
  end

  def as_json(options)
    json = super(options)
    json[:name] = title
    json[:text] = title
    json
  end

  def self.sortable_column_names
    %w[title author created_at updated_at]
  end

  private
  def can_destroy?
    if self.solutions.length > 0
      errors.add(:base, I18n.t("solution_specs.cannot_delete"))
      return false
    else
      return true
    end
  end

  def can_unpublish?
    if !self.published && self.solutions.length > 0
      errors.add(:base, I18n.t("solution_specs.cannot_unpublished"))
      return false
    else
      return true
    end
  end
end

app/controllers/solution_specializations_controller.rb
class SolutionSpecializationsController < BaseController
  #GET /solution_specializations
  #getting all solutions in the system
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || PER_PAGE
    @sort_column = sort_column
    @direction = sort_direction
    params[:q] = params[:q] || ''
    params[:type] = params[:type] || 'all'

    if @sort_column == "author"
      sort_col = "users.full_name #{@direction}, users.email"
    else
      sort_col = @sort_column
    end

    @solution_specs = SolutionSpecialization.search(params[:q], params[:type])
      .joins("LEFT JOIN users on author_id = users.id")
      .paginate(:page => page, :per_page => per_page)
      .order("#{sort_col} #{@direction}")

    respond_to do |format|
      format.html{}
      format.json do
        @solution_specs = [SolutionSpecialization.new({:id => 0,
          "title" => t("solution_specs.default_title")})].concat(@solution_specs) if params[:add_more]
        render :json => @solution_specs
      end
    end
  end

  #PUT /solution_specializations/:id/toggle_status
  #Change status of solution
  def toggle_status
    if @solution_specialization.toggle_status
      action = @solution_specialization.published? ? "published" : "unpublished"
      redirect_to solution_specializations_path, :notice => t("solution_specs.#{action}_successfully")
    else
      redirect_to solution_specializations_path, :alert => t("solution_specs.cannot_unpublished")
    end
  end

  #DELETE /solution_specializations/:id
  def destroy
    if @solution_specialization.destroy
      redirect_to solution_specializations_path, :notice => t("solution_specs.deleted_successfully")
    else
      redirect_to solution_specializations_path, :alert => t("solution_specs.cannot_delete")
    end
  end

  #GET /solution_specializations/new
  def new
    @solution_specialization = SolutionSpecialization.new
    @solution_specialization.published = true
  end

  #POST /solution_specializations
  def create
    params[:solution_specialization][:author_id] = current_user.id
    @solution_specialization = SolutionSpecialization.new(solution_spec_params)
    if @solution_specialization.save
      redirect_to solution_specializations_path, :notice => t("solution_specs.created_successfully")
    else
      render :new
    end
  end

  #GET /solution_specializations/:id/edit
  def edit
  end

  #PUT /solution_specializations/:id
  def update
    if @solution_specialization.update_attributes(solution_spec_params)
      redirect_to solution_specialization_path(@solution_specialization),
        :notice => t("solution_specs.updated_successfully")
    else
      render :edit
    end
  end

  #GET /solution_specializations/:id
  def show
  end

private
  def solution_spec_params
    params.require(:solution_specialization).permit(:title,
      :published, :author_id)
  end

  def sort_column
    SolutionSpecialization.sortable_column_names.include?(params[:sort_column]) ?
      params[:sort_column] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/solution_specializations_helper.rb
module SolutionSpecializationsHelper
end

app/views/solution_specializations/_solution_spec_form.html.erb
<%= form_errors(solution_spec) %>
<%= simple_form_for(solution_spec, :html => {:role => 'form', :class => "solution-form" }) do |f| %>
  <fieldset>
    <%= form_control_wrapper do %>
      <%= f.input :title, :input_html => { autofocus: true } %>
    <% end %>

    <div class='row'>
      <div class='col-md-12'>
        <div class='form-group'>
          <%= f.label :published, :class => "control-label" %>
          <div class='row radio no-margin-top'>
            <div class='col-md-2'>
              <label>
                <%= f.radio_button :published, 1, :checked => solution_spec.published? %>
                <%= t(".published") %>
              </label>
            </div>
            <div class='col-md-2'>
              <label>
                <%= f.radio_button :published, 0, :checked => !solution_spec.published? %>
                <%= t(".unpublished") %>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
  <%= form_control_wrapper do %>
    <%= f.submit t(".save"), class: "btn btn-primary" %>
    <%= button_tag t(".cancel"), type: "button", class: "btn btn-default", onclick: "window.location='#{solution_specializations_path}'" %>
  <% end %>
<% end %>

app/views/solution_specializations/edit.html.erb
<div class="row">
  <div class='col-md-12'>
    <ol class="breadcrumb">
      <li><a href="<%= solution_specializations_path %>"><%= t("solution_specializations.list") %></a></li>
      <li><%= t(".header") %></li>
    </ol>
  </div>
</div>
<%= render :partial => "solution_spec_form", :locals => {:solution_spec => @solution_specialization} %>

app/views/solution_specializations/index.html.erb
<div class="row">
  <div class="col-md-9">
    <ol class="breadcrumb">
      <li><%= t("solution_specializations.list") %></li>
    </ol>
  </div>
  <div class="col-md-3 pull-right text-right">
    <a type="button" class="btn btn-primary full-width" href="<%= new_solution_specialization_path %>"><%= t("solution_specializations.create") %></a>
  </div>
</div>
<div class="row">
  <div class='col-md-12'>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @solution_specs.total_entries %>
          <table class="table table-striped table-bordered">
            <thead>
              <th class='solution-title-column'>
                <%= sortable_column(t(".spec_title"), :title, @sort_column, @direction,params, 'spec') %>
                <%= sort_icon(:title, @sort_column, @direction) %>
              </th>
              <th>
                 <%= sortable_column(t(".author"), :author, @sort_column, @direction, params, 'spec') %>
                <%= sort_icon(:author, @sort_column, @direction) %>
              </th>
              <th>
                <%= sortable_column(t(".created_at"), :created_at, @sort_column, @direction, params, 'spec') %>
                <%= sort_icon(:created_at, @sort_column, @direction) %>
              </th>
              <th>
                <%= sortable_column(t(".status"), :published, @sort_column, @direction, params, 'spec') %>
                <%= sort_icon(:published, @sort_column, @direction) %>
              </th>
              <th>
                Action
              </th>
            </thead>
            <tbody>
              <% @solution_specs.each do |solution| %>
                <tr>
                  <td>
                    <%= display_long_string(solution.title, 30) %>
                  </td>
                  <% name = solution.author.name if solution.author %>
                  <td><%= display_long_string(name,30) %></td>
                  <td><%= solution.created_at.strftime(DATE_FORMAT) %></td>
                  <td><%= solution.published? ? t("common.published") : t("common.unpublished") %></td>
                  <td>
                    <%= link_to '', solution_specialization_path(solution), :class => "glyphicon glyphicon-th-large", :title => t(".title.view") %>

                    <%= link_to '', edit_solution_specialization_path(solution), :class => "glyphicon glyphicon-pencil edit-spec", :title => t(".title.edit"), :id => "btn-edit-#{solution.id}" %>
                    <% action = solution.published? ? t("common.unpublish") : t("common.publish") %>
                    <% text_color = !solution.published? ? 'text-muted' : '' %>
                    <%= link_to '', {:action => :toggle_status, :id => solution.id, :page => @page}, :method => :put, :class => "glyphicon glyphicon-ok #{text_color} toggle-status", data: {:confirm => t(".confirm.#{action}", :name => solution.title)}, :title => t(".title.#{action}") %>
                    <%= link_to '', {:action => :destroy, :id => solution.id, :page => @page}, :method => :delete, :class => "glyphicon glyphicon-trash delete-spec", :title => t(".title.delete"), data: {:confirm => t(".confirm.delete", :name => solution.title) } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
      <% if @solution_specs.total_entries > 0 %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <div class='pagination-info'>
                 <%= page_entries_info(@solution_specs) if @solution_specs.length > 0 %>
              </div>
            </div>
            <div class="col-md-6 pull-right text-right">
              <%= will_paginate(@solution_specs, renderer: BootstrapPagination::Rails, bootstrap: 3) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/solution_specializations/new.html.erb
<div class="row">
  <div class='col-md-12'>
    <ol class="breadcrumb">
      <li><a href="<%= solution_specializations_path %>"><%= t("solution_specializations.list") %></a></li>
      <li><%= t("solution_specializations.create") %></li>
    </ol>
  </div>
</div>
<%= render :partial => "solution_spec_form", :locals => {:solution_spec => @solution_specialization} %>

app/views/solution_specializations/show.html.erb
<%= form_control_wrapper do %>
    <ol class="breadcrumb">
      <li><a href="<%= solution_specializations_path %>"><%= t("solution_specializations.list") %></a></li>
      <li><%= t(".header") %></li>
    </ol>
<% end %>
<%= form_control_wrapper do %>
  <label><%= SolutionSpecialization.human_attribute_name(:title) %></label>
  </br>
  <%= @solution_specialization.title %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <label for="solution_title"><%= SolutionSpecialization.human_attribute_name(:published) %></label>
  </br>
    <%= @solution_specialization.published? ? t("common.published") : t("common.unpublished") %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <a href="<%= edit_solution_specialization_path(@solution_specialization) %>" class="btn btn-primary" ><%= t("common.edit") %></a>
<% end %>