config/routes.rb
Sample::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout',
    :password => 'secret', :confirmation => 'verification', :registration => 'register' }, :controllers => {:registrations => "authentication"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users do
    member do
      put 'toggle_status'
    end
  end

  resources :solutions do
    member do
      put 'toggle_status'
    end
    collection do
      get 'search_authors'
      get 'search_specs'
    end
  end

  resources :home

  resources :solution_specializations do
    member do
      put 'toggle_status'
    end
  end
end

app/models/user.rb
require 'net/http'
class User < ActiveRecord::Base
  rolify

  ### CONSTANTS ###
  STATUS = {
    :published => "published",
    :unpublished => "unpublished"
  }

  ### INCLUDES DEFAULT DEVISE MODULE ###
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  ### VALIDATIONS ###
  validates_numericality_of :karma, :greater_than => 0, :less_than => 5001, :allow_blank => true, :message => I18n.t("users.error_on_karma")
  validate :avatar_is_less_than_two_megabytes
  validates_length_of :full_name, maximum: 100
  validates_length_of :email, maximum: 255
  validates_length_of [:about, :additional_info], maximum: 5001

  after_save :switch_role
  before_destroy :can_destroy

  ### ASSOCIATIONS ###
  has_many :solutions, :foreign_key => "author_id", dependent: :destroy
  has_many :solution_specializations, :foreign_key => "author_id", dependent: :destroy
  has_one :contact, dependent: :destroy
  accepts_nested_attributes_for :contact

  has_attached_file :avatar, :styles => { :thumb => "100x100#", :large => "600x600>" },
  :default_style => :thumb, default_url: "avatar_missing.png"
  validates_attachment_content_type :avatar, :content_type=>['image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/jpg']

  attr_accessor :role

  scope :search, lambda { |keyword|
    where("published = TRUE AND (LOWER(full_name) LIKE :keyword OR LOWER(email) LIKE :keyword)", {keyword: "%#{keyword.downcase}%"})
  }

  ### FUNCTIONS ###

  def is_admin?
    return has_role?(:super_admin) || has_role?(:admin)
  end

  def active_for_authentication?
    super && self.published?
  end

  def inactive_message
    self.published? ? super : :unpublished
  end

  #display full name or email
  def name
    if full_name.blank?
      email
    else
      full_name
    end
  end

  #Getting avatar url from local or from Gravatar
  def avatar_url
    if avatar.exists?
      avatar.url(:thumb)
    else
      gravatar_id = Digest::MD5.hexdigest(email.downcase)
      gravatar_check = "http://gravatar.com/avatar/#{gravatar_id}.png?s=100&d=404"
      uri = URI.parse(gravatar_check)
      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)
      response = http.request(request)
      if (response.code.to_i == 404)
        avatar.url(:thumb)
      else
        gravatar_check
      end
    end
  end

  def as_json(options)
    json = super(options)
    json[:name] = name
    json
  end

  #Change status of this solution from published to unpublished vice versa
  def toggle_status
    self.published = !published
    self.save
  end

  def self.invite_user params
    password = Devise.friendly_token[0,20]
    params[:password] = password
    params[:password_confirmation] = password

    user = User.new(params)
    user.reset_password_token   = Devise.friendly_token[0,20]
    user.reset_password_sent_at = Time.now.utc
    user
  end

private
  def avatar_is_less_than_two_megabytes
    if self.avatar?
      if self.avatar.size > 2.megabytes
        errors.add(:avatar, I18n.t("users.avatar_file_size_validation"))
      end
    end
  end

  def switch_role
    if self.role
      self.roles = []
      self.add_role(Role.find(self.role).name)
    end
  end

  def can_destroy
    if self.solutions.length > 0 || self.solution_specializations.length > 0
      errors.add(:base, I18n.t("users.cannot_delete_user"))
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController

  ##
  #Handle index request get list of user
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || PER_PAGE

    @users = @users.where.not(id: current_user.id).paginate(page: page, per_page: per_page).order("email, full_name")
  end

  ##
  #Handle show user details by administrator
  def show
    @roles = Role.all
    @user.build_contact if @user.contact.nil?
  end

  ##
  #Handle new user by administrator
  def new
    @user = User.new
    @user.build_contact
    @roles = Role.accessible_roles
  end

  ##
  #Handle edit user by administrator
  def edit
    @user.build_contact unless @user.contact
    @roles = Role.accessible_roles
    @user.role = @user.role_ids[0]
  end

  ##
  #Handle update user by administrator
  #Return::
  #
  def update
    if @user.update_attributes(user_params)
      if params[:id].to_i == current_user.id
        flash[:notice] = t("users.update_profile_successfully")
        redirect_to user_path(current_user)
      else
        flash[:notice] = t("users.update_user_successfully")
        redirect_to users_path
      end
    else
      @roles = Role.accessible_roles
      @user.role = @user.role_ids[0]
      render :edit
    end
  end

  ##
  #Handle create user by administrator
  def create
    @user = User.invite_user user_params
    if @user.save
      flash[:notice] = t('users.created_successfully')
      redirect_to users_path
    else
      @roles = Role.accessible_roles
      @user.role = @user.role_ids[0]
      render :new
    end
  end

  ##
  #Handle destroy request destroy a user
  def destroy
    @page = params[:page] || 1
    if @user.destroy
      redirect_to(users_url(:page => @page), :notice => t("users.deleted_successfully"))
    else
      redirect_to(users_url(:page => @page), :alert => t("users.cannot_delete_user"))
    end
  end

  ##
  #Handle publish or unpublish a user
  def toggle_status
    desired_status = @user.published? ? User::STATUS[:unpublished] : User::STATUS[:published]
    @page = params[:page] || 1
    if @user.toggle_status
      redirect_to(users_url(:page => @page), :notice => t("users.#{desired_status}_successfully"))
    else
      redirect_to(users_url(:page => @page), :alert => t("users.cannot_#{desired_status}"))
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :role, {:role_ids => []}, :password, :password_confirmation,
      :remember_me, :full_name, :karma, :services, :about, :additional_info,
      :published, :email, :avatar, contact_attributes:[:id, :city, :country, :phone,
        :address, :skype, :facebook_link, :vkontakte_link, :twitter_link,
        :linkedin_link, :website_link])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<% if !user.errors.empty? %>
  <div class="row">
    <div class='col-md-12'>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
         <% user.errors.full_messages.each do |m| %>
            <%= m %>.
          </br>
         <% end %>
      </div>
    </div>
  </div>
<% end %>

<%= simple_form_for(user, role: "form", html: {:class => "user-form"} ) do |f| %>
   <fieldset>
    <%= form_control_wrapper(class: "col-md-6") do %>
      <%= f.input :full_name, input_html: { autofocus: true } %>
    <% end %>
    <%= form_control_wrapper do %>
      <div class='form-group'>
        <%= f.label :published, :class => "control-label" %>
        <div class='row radio no-margin-top'>
          <div class='col-md-2'>
            <label>
              <%= f.radio_button :published, 1, :checked => user.published? %>
              <%= t(".published") %>
            </label>
          </div>
          <div class='col-md-2'>
            <label>
              <%= f.radio_button :published, 0, :checked => !user.published? %>
              <%= t(".unpublished") %>
            </label>
          </div>
        </div>
      </div>
    <% end %>

    <% unless @user.id == current_user.id %>
      <%= form_control_wrapper(class: "col-md-6") do  %>
        <div class="form-group">
          <%= f.label :user_group %>
          <%= f.select :role, options_for_select(@roles.collect{|r| [r.name.classify, r.id]}, @user.role), {}, :class => "form-control" %>
        </div>
      <% end %>
    <% end %>
    <div class = "row">
      <div class = "col-md-2">
        <div>
          <div class = "inline-block">
            <%= image_tag @user.avatar_url, size: "100x100", :class => 'user-avatar' %>
          </div>
          <div class = "inline-block">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div>
          <span class = "btn btn-primary fileinput-button">
            <%= t(".change_avatar") %>
            <%= f.file_field :avatar %>
          </span>
        </div>
        <div>
          <div class='inline-block' id='file-name'></div>
          <div class='inline-block'>
            <a type="button" class="close hidden" id="btn-remove-avatar">&times;</a>
          </div>
        </div>

        <br/>
      </div>
    </div>

    <%= form_control_wrapper(class: "col-md-6") do %>
      <%= f.input :karma %>
    <% end %>

    <%= form_control_wrapper do %>
      <%= f.input :services, as: :text, :input_html => {rows: 5} %>
    <% end %>
    <div class = "row">
      <div class='col-md-12'>
        <fieldset class = "well white-bg">
          <legend class = "border smaller-margin"><%= t(".contacts") %></legend>
          <div class = "row no-margin">
            <%= f.fields_for :contact do |c| %>

              <div class = "row no-margin">
                <div class = "col-md-6">
                  <%= form_control_wrapper do %>
                    <%= c.input :city %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <div class="form-group">
                      <%= c.label :country %>
                      <%= c.country_select("country", ["us"], {iso_codes: true}, {class: "form-control"}) %>
                    </div>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :phone %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= f.input :email, required: true %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :address %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :skype %>
                  <% end %>
                </div>

                <div class = "col-md-6 pull-right">
                  <%= form_control_wrapper do %>
                    <%= c.input :facebook_link, as: :string %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :vkontakte_link, as: :string %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :twitter_link, as: :string %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :linkedin_link, as: :string %>
                  <% end %>
                  <%= form_control_wrapper do %>
                    <%= c.input :website_link, as: :string %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      </div>
    </div>

    <%= form_control_wrapper do %>
      <%= f.input :about, as: :text, :input_html => {rows: 5} %>
    <% end %>

    <%= form_control_wrapper do %>
      <%= f.input :additional_info, as: :text, :input_html => {rows: 5} %>
    <% end %>
    <br/>
    <div class = "row">
      <div class='col-md-12'>
        <% if user.new_record? %>
          <%= button_tag t(".create"), class: "btn btn-primary" %>
        <% else %>
          <%= button_tag t(".update"), class: "btn btn-primary" %>
        <% end %>
        <%= button_tag t(".cancel"), {class: "btn btn-default", onclick: "location='#{users_path}'; return false;"} %>
      </div>
    </div>
   </fieldset>
<% end %>

app/views/users/edit.html.erb
<div class = "normal-form" id = "create_user_wrapper">
  <div class="row">
    <div class='col-md-12'>
      <ol class="breadcrumb">
        <li><a href="<%= users_path %>"><%= t("users.list") %></a></li>
        <li><%= t(".header") %></li>
      </ol>
    </div>
  </div>
  <%= render "user_form", :user => @user, :action => "edit" %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-10">
    <ol class="breadcrumb">
      <li><%= t("users.list") %></li>
    </ol>
  </div>
  <div class="col-md-2 pull-right text-right">
    <a type="button" class="btn btn-primary full-width" href="<%= new_user_path %>"><%= t("users.create") %></a>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <% if @users.total_entries > 0 %>
      <table class="table table-striped table-bordered">
        <thead>
          <th class="col-md-4"><%= t('.email') %></th>
          <th class="col-md-3"><%= t('.fullname') %></th>
          <th class="con-md-2"><%= t('.status') %></th>
          <th class="col-md-2"><%= t('.group') %></th>
          <th class="con-md-1"><%= t('.common.action') %></th>
        </thead>
        <tbody>
          <% @users.each do |u| %>
            <tr>
              <td><%= display_long_string(u.email,30) %></td>
              <td><%= display_long_string(u.full_name,30) %></td>
              <td><%= u.published? ? t("common.published") : t("common.unpublished") %></td>
              <td><%= u.roles[0].name.classify %></td>
              <td>
                <%= link_to '', user_path(u), :class => "glyphicon glyphicon-th-large", :title => t(".title.view") %>

                <%= link_to '', edit_user_path(u), :class => "glyphicon glyphicon-pencil", :title => t(".title.edit"), :id => "btn-edit-#{u.id}" %>
                <% action = u.published? ? 'unpublish' : 'publish' %>
                <% text_color = !u.published? ? 'text-muted' : '' %>
                <%= link_to '', {:action => :toggle_status, :id => u.id, :page => @page}, :method => :put, :class => "glyphicon glyphicon-ok #{text_color}", :title => t(".title.#{action}"), data: {:confirm => t(".confirm.#{action}", :name => u.name)}, :id => "btn-status-#{u.id}" %>
                <%= link_to '', {:action => :destroy, :id => u.id, :page => @page}, :method => :delete, :class => "glyphicon glyphicon-trash", :title => t(".title.delete"), data: {:confirm => t(".confirm.delete", :name => u.name)}, :id => "btn-delete-#{u.id}" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <%= t(".no_user") %>
    <% end %>
  </div>
  <% if @users.total_entries > 0 %>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-6">
          <div class='pagination-info'>
            <%= page_entries_info(@users) %>
          </div>
        </div>
        <div class="col-md-6 pull-right text-right">
          <%= will_paginate(@users, renderer: BootstrapPagination::Rails, bootstrap: 3) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class = "normal-form" id = "create_user_wrapper">
  <div class="row">
    <div class='col-md-12'>
      <ol class="breadcrumb">
        <li><a href="<%= users_path %>"><%= t("users.list") %></a></li>
        <li><%= t("users.create") %></li>
      </ol>
    </div>
  </div>
  <%= render "user_form", :user => @user %>
</div>

app/views/users/show.html.erb
<%= form_control_wrapper do %>
  <ol class="breadcrumb">
    <li><a href="<%= users_path %>"><%= t("users.list") %></a></li>
    <li><%= t(".header") %></li>
  </ol>
<% end %>
<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:fullname) %></b>
  </br>
  <%= @user.full_name %>
<% end %>
</br>

<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:published) %></b>
  </br>
  <%= @user.published? ? t("common.published") : t("common.unpublished") %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:user_group) %></b>
  </br>
  <%= @user.roles[0].name.classify if @user.roles[0] %>
<% end %>
<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:avatar) %></b>
  </br>
  <%= image_tag @user.avatar_url, size: "100x100" %>
<% end %>

<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:karma) %></b>
  </br>
  <%= @user.karma %>
<% end %>
</br>

<%= form_control_wrapper do %>
  <b><%= User.human_attribute_name(:services) %></b>
  </br>
  <%= @user.services %>
<% end %>
<%= form_control_wrapper do %>
  <fieldset class = "well white-bg">
    <legend class = "border smaller-margin"><%= Contact.model_name.human %></legend>
      <div class = "row no-margin">
        <div class = "col-md-6">
          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:city) %></b>
            <br/>
            <%= @user.contact.city %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:country) %></b>
            <br/>
            <%= IsoCountryCodes.find(@user.contact.country).name if @user.contact.country %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:phone) %></b>
            <br/>
            <%= @user.contact.phone %>
          </div>

          <div class = "form-group">
            <b><%= User.human_attribute_name(:email) %></b>
            <br/>
            <%= @user.email %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:address) %></b>
            <br/>
            <%= @user.contact.address %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:skype) %></b>
            <br/>
            <%= @user.contact.skype %>
          </div>
        </div>

        <div class = "col-md-6 pull-right">
          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:facebook_link) %></b>
            <br/>
            <%= @user.contact.facebook_link %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:vkontakte_link) %></b>
            <br/>
            <%= @user.contact.vkontakte_link %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:twitter_link) %></b>
            <br/>
            <%= @user.contact.twitter_link %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:linkedin_link) %></b>
            <br/>
            <%= @user.contact.linkedin_link %>
          </div>

          <div class = "form-group">
            <b><%= Contact.human_attribute_name(:website_link) %></b>
            <br/>
            <%= @user.contact.website_link %>
          </div>
        </div>
      </div>
<% end %>

    <div class = "row">
      <div class = "col-md-12">
        <div class = "form-group">
          <b><%= User.human_attribute_name(:about) %></b>
          <br/>
          <%= @user.about %>
        </div>
      </div>
    </div>

    <div class = "row">
      <div class = "col-md-12">
        <div class = "form-group">
          <div class = "form-group">
            <b><%= User.human_attribute_name(:additional_info) %></b>
            <br/>
            <%= @user.additional_info %>
          </div>
        </div>
      </div>
    </div>
    <br/>
    <div class = "row">
      <div class='col-md-12'>
        <a href="<%= edit_user_path(@user) %>" class="btn btn-primary" type="button"><%= t(".edit") %></a>
      </div>
    </div>
</div>