config/routes.rb
Sample::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout',
    :password => 'secret', :confirmation => 'verification', :registration => 'register' }, :controllers => {:registrations => "authentication"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users do
    member do
      put 'toggle_status'
    end
  end

  resources :solutions do
    member do
      put 'toggle_status'
    end
    collection do
      get 'search_authors'
      get 'search_specs'
    end
  end

  resources :home

  resources :solution_specializations do
    member do
      put 'toggle_status'
    end
  end
end

app/models/solution.rb
class Solution < ActiveRecord::Base

  ### VALIDATIONS ###
  validates_presence_of :title
  validate :image_is_less_than_two_megabytes
  validates_length_of :title, :maximum => 255
  validates_length_of :favor, :maximum => 255, :allow_blank => true
  validates_length_of [:teaser, :full_text], :maximum => 5000, :allow_blank => true

  ### ASSOCIATIONS ###
  belongs_to :author, :class_name => :User
  has_many :tasks, :dependent => :destroy
  has_and_belongs_to_many :specializations, :class_name => :SolutionSpecialization, :join_table => "solutions_specs", :association_foreign_key => "spec_id"

  has_attached_file :image, :styles => {:thumb => "100x100#", :large => "600x600>"},
    default_url: "solution_default.png"
  validates_attachment_content_type :image, :content_type => ["image/jpeg", "image/png",
    "image/gif", "image/bmp", "image/jpg"]

  attr_reader :specialization_tokens

  accepts_nested_attributes_for :tasks, :reject_if => lambda{|t| t[:title].blank? }, :allow_destroy => true

  ### FUNCTIONS ###

  #Change status of this solution from published to unpublished vice versa
  def toggle_status
    self.published = !published
    self.save
  end

  def specialization_tokens=(ids)
    self.specialization_ids = ids.split(",")
  end

  def self.sortable_column_names
    %w[title author published favor created_at updated_at]
  end

  private
  def image_is_less_than_two_megabytes
    if self.image?
      if self.image.size > 2.megabytes
        errors.add(:image, I18n.t("solutions.image_file_size_validation"))
      end
    end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < BaseController

  #GET /solutions
  #getting all solutions in the system
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || PER_PAGE
    @sort_column = sort_column
    @direction = sort_direction

    if params[:spec_id]
      if params[:spec_id].to_i == 0
        @spec = SolutionSpecialization.new({:id => 0, "title" => t("solution_specs.default_title")})
      else
        @spec = SolutionSpecialization.find(params[:spec_id])
      end
    end

    @solutions = Solution.scoped

    if @sort_column == "author"
      sort_col = "users.full_name #{@direction}, users.email"
    else
      sort_col = @sort_column
    end

    if params[:spec_id] && params[:spec_id].to_i != 0
      @solutions = @solutions.joins(:specializations).where("solution_specializations.id" => params[:spec_id])
    end

    @solutions = @solutions.joins("LEFT JOIN users ON solutions.author_id = users.id")
      .paginate(:page => page, :per_page => per_page, :select => "solutions.*")
      .order("#{sort_col} #{@direction}")
  end

  #PUT /solutions/:id/toggle_status
  #Change status of solution
  def toggle_status
    @solution.toggle_status
    action = @solution.published? ? "published" : "unpublished"
    redirect_to solutions_path, :notice => t("solutions.#{action}_successfully")
  end

  #DELETE /solutions/:id
  def destroy
    @solution.destroy
    redirect_to solutions_path, :notice => t("solutions.deleted_successfully")
  end

  #GET /solutions/new
  def new
    @solution = Solution.new
    @solution.published = true
  end

  #POST /solutions
  def create
    @solution = Solution.new(solution_params)
    if @solution.save
      redirect_to solutions_path, :notice => t("solutions.created_successfully")
    else
      @solution.image = nil
      render :new
    end
  end

  #GET /solutions/:id/edit
  def edit
  end

  #PUT /solutions/:id
  def update
    if @solution.update_attributes(solution_params)
      redirect_to solution_path(@solution), :notice => t("solutions.updated_successfully")
    else
      render :edit
    end
  end

  #GET /solutions/:id
  def show
  end

  #Search users to assign as authors
  def search_authors
    @users = User.search(params[:q])
    render :json => @users
  end

  private
  def solution_params
    params.require(:solution).permit(:title, :teaser, :favor, :full_text,
      :published, :image, :author_id, :specialization_tokens, :tasks_attributes => [:title, :_destroy, :id])
  end

  def sort_column
    Solution.sortable_column_names.include?(params[:sort_column].to_s) ? params[:sort_column] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/solutions_helper.rb
module SolutionsHelper
  #Display sort icon on solution list
  def sort_icon(current_field, sorted_field, direction)
    if current_field == sorted_field.to_sym
      arrow = (direction.downcase == "asc") ? "up" : "down"
      content_tag(:i, '', :class => "sort-icon glyphicon glyphicon-chevron-#{arrow}")
    end
  end

  def sortable_column(text, field, sorted_field, direction, params, type = 'solution')
    if sorted_field.to_sym == field
      new_direction = direction.downcase == "asc" ? "desc" : "asc"
    else
      new_direction = "asc"
    end
    if type == 'solution'
      return link_to text, solutions_path(params.merge(:sort_column => field, :direction => new_direction))
    else
      return link_to text, solution_specializations_path(params.merge(:sort_column => field, :direction => new_direction))
    end
  end
end

app/views/solutions/_solution_form.html.erb
<%= form_errors(solution) %>
<%= simple_form_for(solution, :html => {:role => 'form', :class => "solution-form" }) do |f| %>
  <fieldset>
    <%= form_control_wrapper do %>
      <%= f.input :title, input_html: { autofocus: true } %>
    <% end %>
    <%= form_control_wrapper do %>
      <div class='form-group'>
        <%= f.label :published, :class => "control-label" %>
        <div class='row radio no-margin-top'>
          <div class='col-md-2'>
            <label>
              <%= f.radio_button :published, 1, :checked => solution.published? %>
              <%= t(".published") %>
            </label>
          </div>
          <div class='col-md-2'>
            <label>
              <%= f.radio_button :published, 0, :checked => !solution.published? %>
              <%= t(".unpublished") %>
            </label>
          </div>
        </div>
      </div>
    <% end %>
    <%= form_control_wrapper do %>
      <%= f.input :favor %>
    <% end %>

    <%= form_control_wrapper do %>
      <div class="form-group">
        <%= f.label :tasks %>
        <% if solution.tasks.length == 0 %>
          <div class="row fields task-field">
            <div class="col-md-10 col-md-offset-1">
              <input class="form-control valid" id="solution_tasks_attributes_0_title" name="solution[tasks_attributes][0][title]" placeholder="<%= t('.placeholder.task_title') %>" type="text">
            </div>
            <div class="col-md-1">
              <input id="solution_tasks_attributes_0__destroy" name="solution[tasks_attributes][0][_destroy]" type="hidden"><a class="action-field-link" href="#" onclick="remove_fields(this); return false;"><%= t(".remove_task") %></a>
            </div>
          </div>
        <% end %>
        <%= f.fields_for :tasks do |builder| %>
          <%= render "task_fields", :f => builder %>
        <% end %>
        <div class="col-md-offset-1"><%= link_to_add_fields t(".add_task"), f, :tasks %></div>
      </div>
    <% end %>
    <%= form_control_wrapper(class: "col-md-6") do %>
      <div class="form-group">
        <%= f.label :specializations, class: "control-label" %>
        <%= f.hidden_field :specialization_tokens , specs: solution.specializations.to_json %>
      </div>
    <% end %>
    <div class = "row">
      <br />
      <div class = "col-md-2">
        <div>
          <div class = "inline-block">
            <%= image_tag solution.image.url, size: "100x100", :class => 'solution-image' %>
          </div>
          <div class = "inline-block">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div>
          <span class = "btn btn-primary fileinput-button">
            <%= t(".change_image") %>
            <%= f.file_field :image %>
          </span>
        </div>
        <div>
          <div class='inline-block' id='file-name'></div>
          <div class='inline-block'>
            <a type="button" class="close hidden" id="btn-remove-solution-image">&times;</a>
          </div>
        </div>
      </div>
    </div>
    <br />
    <%= form_control_wrapper do %>
      <%= f.input :teaser, as: :text, :input_html => {rows: 5} %>
    <% end %>
    <%= form_control_wrapper do %>
      <%= f.input :full_text, as: :text, :input_html => {rows: 5} %>
    <% end %>
    <%= form_control_wrapper(class: "col-md-6") do %>
      <div class="form-group">
        <%= f.label :author, class: "control-label" %>
        <%= f.text_field :author_id, value: (solution.author.name if solution.author) %>
      </div>
    <% end %>
  </fieldset>
  <%= form_control_wrapper do %>
      <%= f.submit t(".save"), class: "btn btn-primary" %>
      <%= button_tag t(".cancel"), type: "button", class: "btn btn-default", onclick: "window.location='#{solutions_path}'" %>
  <% end %>
<% end %>

app/views/solutions/_task_fields.html.erb
<div class="row fields task-field">
  <div class="col-md-10 col-md-offset-1">
    <%= f.text_field :title, placeholder: t("solutions.solution_form.placeholder.task_title"), class: "form-control" %>
  </div>
  <div class="col-md-1">
    <%= link_to_remove_fields t("solutions.solution_form.remove_task"), f %>
  </div>
</div>

app/views/solutions/edit.html.erb
<div class="row">
  <div class='col-md-12'>
    <ol class="breadcrumb">
      <li><a href="<%= solutions_path %>"><%= t("solutions.list") %></a></li>
      <li><%= t(".header") %></li>
    </ol>
  </div>
</div>
<%= render :partial => "solution_form", :locals => {:solution => @solution} %>

app/views/solutions/index.html.erb
<%= javascript_include_tag 'solutions' %>
<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li><%= t("solutions.list") %></li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <%= form_tag(solutions_path, method: "get") do %>
    <%= hidden_field_tag(:spec_id, "#{@spec.id if @spec}", spec: "#{@spec.title if @spec}") %>
    <% params.each do |key, value| %>
      <% if key.to_s != "spec_id" && key.to_s != "page" %>
        <%= hidden_field_tag(key, value)%>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= submit_tag(t(".filter"), class: "from-control btn btn-primary") %>
  </div>
  <div class="col-md-3 pull-right text-right">
    <a type="button" class="btn btn-primary " href="<%= new_solution_path %>"><%= t("solutions.create") %></a>
  </div>
<% end %>
</div>
</br>
<div class="row">
  <div class='col-md-12'>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @solutions.total_entries %>
          <table class="table table-striped table-bordered">
            <thead>
              <th class='solution-title-column col-md-4'>
                <%= sortable_column(t(".solution_title"), :title, @sort_column, @direction,params) %>
                <%= sort_icon(:title, @sort_column, @direction) %>
              </th>
              <th>
                 <%= sortable_column(t(".author"), :author, @sort_column, @direction, params) %>
                <%= sort_icon(:author, @sort_column, @direction) %>
              </th>
              <th class="col-md-1">
                 <%= sortable_column(t(".favor"), :favor, @sort_column, @direction, params) %>
                <%= sort_icon(:favor, @sort_column, @direction) %>
              </th>
              <th>
                <%= sortable_column(t(".created_at"), :created_at, @sort_column, @direction, params) %>
                <%= sort_icon(:created_at, @sort_column, @direction) %>
              </th>
              <th>
                <%= sortable_column(t(".last_edited_at"), :updated_at, @sort_column, @direction, params) %>
                <%= sort_icon(:updated_at, @sort_column, @direction) %>
              </th>
              <th>
                <%= sortable_column(t(".status"), :published, @sort_column, @direction, params) %>
                <%= sort_icon(:published, @sort_column, @direction) %>
              </th>
              <th>
                <%= t("common.action") %>
              </th>
            </thead>
            <tbody>
              <% @solutions.each do |solution| %>
                <tr>
                  <td>
                    <%= display_long_string(solution.title,30) %>
                  </td>
                  <% name = solution.author.name if solution.author %>
                  <td><%= display_long_string(name,25) %></td>
                  <td><%= display_long_string(solution.favor,10) %></td>
                  <td><%= solution.created_at.strftime(DATE_FORMAT) %></td>
                  <td><%= solution.updated_at.strftime(DATE_FORMAT) %></td>
                  <td><%= solution.published? ? t("common.published") : t("common.unpublished") %></td>
                  <td>
                    <%= link_to '', solution_path(solution), :class => "glyphicon glyphicon-th-large", :title => t(".title.view") %>

                    <%= link_to '', edit_solution_path(solution), :class => "glyphicon glyphicon-pencil update-solution", :title => t(".title.edit"), :id => "btn-edit-#{solution.id}" %>
                    <% action = solution.published? ? t("common.unpublish") : t("common.publish") %>
                    <% text_color = !solution.published? ? 'text-muted' : '' %>
                    <%= link_to '', {:action => :toggle_status, :id => solution.id, :page => @page}, :method => :put, :class => "glyphicon glyphicon-ok #{text_color} toggle-status", data: {:confirm => t(".confirm.#{action}", :name => solution.title)}, :title => t(".title.#{action}") %>
                    <%= link_to '', {:action => :destroy, :id => solution.id, :page => @page}, :method => :delete, :class => "glyphicon glyphicon-trash delete-solution", :title => t(".title.delete"), data: {:confirm => t(".confirm.delete", :name => solution.title) } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
      <% if @solutions.total_entries > 0 %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <div class='pagination-info'>
                <%= page_entries_info(@solutions) if @solutions.length > 0 %>
              </div>
            </div>
            <div class="col-md-6 pull-right text-right">
              <%= will_paginate(@solutions, renderer: BootstrapPagination::Rails, bootstrap: 3) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/solutions/new.html.erb
<div class="row">
  <div class='col-md-12'>
    <ol class="breadcrumb">
      <li><a href="<%= solutions_path %>"><%= t("solutions.list") %></a></li>
      <li><%= t("solutions.create") %></li>
    </ol>
  </div>
</div>
<%= render :partial => "solution_form", :locals => {:solution => @solution} %>

app/views/solutions/show.html.erb
<%= form_control_wrapper do %>
  <ol class="breadcrumb">
    <li><a href="<%= solutions_path %>"><%= t("solutions.list") %></a></li>
    <li><%= t(".header") %></li>
  </ol>
<% end %>
<%= form_control_wrapper do %>
  <label><%= Solution.human_attribute_name(:title) %></label>
  </br>
  <%= @solution.title %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <label for="solution_title"><%= Solution.human_attribute_name(:published) %></label>
  </br>
  <%= @solution.published? ? t("common.published") : t("common.unpublished") %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <label for="solution_title"><%= Solution.human_attribute_name(:favor) %></label>
  </br>
  <%= @solution.favor %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <b><%= Solution.human_attribute_name(:tasks) %></b>
  <% @solution.tasks.each do |task| %>
    <div class="col-md-offset-1">
      <%= task.title %>
    </div>
  <% end %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <b><%= Solution.human_attribute_name(:specializations) %></b>
  <% @solution.specializations.each do |spec| %>
    <div class="col-md-offset-1">
      <%= spec.title %>
    </div>
  <% end %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <b><%= Solution.human_attribute_name(:image) %></b>
  </br>
  <%= image_tag @solution.image.url(:thumb), size: "100x100", :class => 'solution-image' %>
<% end %>
<br />
<%= form_control_wrapper do %>
  <label><%= Solution.human_attribute_name(:teaser) %></label>
  </br>
  <%= @solution.teaser %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <label><%= Solution.human_attribute_name(:full_text) %></label>
  </br>
  <%= @solution.full_text %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <label><%= Solution.human_attribute_name(:author) %></label>
  </br>
  <%= @solution.author.name if @solution.author %>
<% end %>
</br>
<%= form_control_wrapper do %>
  <a href="<%= edit_solution_path(@solution) %>" class="btn btn-primary" type="button"><%= t("solutions.solution_form.edit") %></a>
<% end %>