config/routes.rb
Sample::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout',
    :password => 'secret', :confirmation => 'verification', :registration => 'register' }, :controllers => {:registrations => "authentication"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users do
    member do
      put 'toggle_status'
    end
  end

  resources :solutions do
    member do
      put 'toggle_status'
    end
    collection do
      get 'search_authors'
      get 'search_specs'
    end
  end

  resources :home

  resources :solution_specializations do
    member do
      put 'toggle_status'
    end
  end
end

app/views/layouts/_dashboard.html.erb
<ul class="nav nav-pills nav-stacked">
  <li><a href="/"><%= t(".dashboard") %></a></li>
  <% if current_user.is_admin? %>
  	<li><a href="<%= users_path %>"><%= t(".user_management") %></a></li>
    <li><a href="<%= solutions_path %>"><%= t(".solution_management") %></a></li>
    <li><a href="<%= solution_specializations_path %>"><%= t(".solution_spec_management") %></a></li>
  <% end %>
</ul>

app/views/layouts/_flash.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="col-md-12">
      <div class="alert alert-dismissable alert-<%= flash_class(level) %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= flash[level] %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_welcomebar.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag("logo.jpeg", :size => "150x100") %>
  </div>
  <div class="col-md-6 pull-right text-right">
    <% if current_user %>
      <%= link_to current_user.name, user_path(current_user) %>&nbsp;
      <%= link_to image_tag(current_user.avatar_url, size: "50x50"), user_path(current_user) %>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li class = "text-left"><%= link_to t(".sign_out"), destroy_user_session_path, method: "delete" %></li>
        </ul>
      </div>
    <% else %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("layouts.site_title") %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/welcomebar" %>
        <div class="row">
          <div class="col-md-12">
            <%= render "layouts/flash" %>
          </div>
        </div>
        <div class="row form-center">
          <div class="col-md-12">
            <%= yield %>
          </div>
        </div>
  </div>
</body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("layouts.site_title") %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/welcomebar" %>
    <div class="row">
      <div class="col-md-2">
        <%= render "layouts/dashboard" %>
      </div>
      <div class="col-md-10">
        <div class = "row">
          <%= render "layouts/flash" %>
        </div>
        <%= yield %>
      </div>
    </div>
    <footer>
      <br />
    </footer>
  </div>
</body>
</html>